/**
 * Component for displaying competitor analysis results
 * Updated to match dashboard dark theme
 */

import { useState } from "react";
import { 
  CheckCircle, 
  FileText, 
  Download, 
  ExternalLink, 
  TrendingUp,
  Users,
  AlertCircle,
  Eye,
  Globe,
  Loader2,
  Sparkles,
  Target,
  BarChart3
} from "lucide-react";
import { type CompetitorAnalysisResponse } from "@/lib/api/competitor";
import { ReportViewer } from "./ReportViewer";
import { downloadReport } from "@/lib/api/competitor";

interface CompetitorResultsProps {
  result: CompetitorAnalysisResponse;
  onReset: () => void;
  businessName: string;
}

export function CompetitorResults({ result, onReset, businessName }: CompetitorResultsProps) {
  const [isReportViewerOpen, setIsReportViewerOpen] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  
  const isSuccess = result.status === "success";
  
  const handleDownloadReport = async () => {
    if (!result.report_path) return;
    
    setIsDownloading(true);
    setDownloadError(null);
    
    try {
      const blob = await downloadReport(result.report_path);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = result.report_path.split('/').pop() || 'competitor_report.txt';
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      setDownloadError(err instanceof Error ? err.message : "Failed to download report");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleViewFullReport = () => {
    setIsReportViewerOpen(true);
  };

  const handleShareResults = () => {
    const shareText = `Competitor Analysis Results for ${businessName}:\n\n${result.result}\n\nGenerated by Credora Analytics`;
    
    if (navigator.share) {
      navigator.share({
        title: `Competitor Analysis - ${businessName}`,
        text: shareText,
      });
    } else {
      navigator.clipboard.writeText(shareText).then(() => {
        alert("Results copied to clipboard!");
      });
    }
  };

  return (
    <div className="space-y-6 animate-slide-up">
      {/* Success/Error Status */}
      <div className="rounded-2xl bg-[#1e1e1e] border border-[#2a2a2a] p-6 transition-all duration-300 hover:border-credora-orange/30">
        <div className="flex items-start gap-4">
          {/* Icon */}
          <div className={`p-3 rounded-xl ${isSuccess ? 'bg-emerald-500/10' : 'bg-red-500/10'}`}>
            {isSuccess ? (
              <CheckCircle className="h-6 w-6 text-emerald-400" />
            ) : (
              <AlertCircle className="h-6 w-6 text-red-400" />
            )}
          </div>

          {/* Content */}
          <div className="flex-1">
            <h2 className="text-xl font-bold text-white mb-1">
              Analysis {isSuccess ? "Complete" : "Failed"}
            </h2>
            <p className="text-gray-400 text-sm mb-4">
              {result.message}
            </p>

            {/* Status Info */}
            <div className="flex flex-wrap items-center gap-3">
              <span className={`px-3 py-1 rounded-lg text-xs font-semibold ${
                isSuccess 
                  ? 'bg-emerald-500/20 text-emerald-400' 
                  : 'bg-red-500/20 text-red-400'
              }`}>
                {result.status.toUpperCase()}
              </span>
              
              {isSuccess && (
                <>
                  <span className="text-sm text-gray-400">
                    <span className="text-white font-medium">{result.competitors_analyzed}</span> competitors analyzed
                  </span>
                  <span className="text-gray-600">•</span>
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <Users className="h-4 w-4" />
                    Analysis for: <span className="text-white font-medium">{businessName}</span>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </div>

      {/* Key Findings */}
      {isSuccess && result.result && (
        <div className="rounded-2xl bg-[#1e1e1e] border border-[#2a2a2a] p-6 transition-all duration-300 hover:border-credora-orange/30">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 rounded-lg bg-credora-orange/10">
              <TrendingUp className="h-5 w-5 text-credora-orange" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-white">Key Findings</h3>
              <p className="text-sm text-gray-500">Strategic insights from competitor analysis</p>
            </div>
          </div>

          <div className="rounded-xl bg-[#282828] border border-[#333] p-5">
            <div className="prose prose-sm max-w-none">
              <div className="whitespace-pre-wrap text-sm text-gray-300 leading-relaxed">
                {result.result}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Comprehensive Report */}
      {isSuccess && result.report_path && (
        <div className="rounded-2xl bg-[#1e1e1e] border border-[#2a2a2a] p-6 transition-all duration-300 hover:border-credora-orange/30">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 rounded-lg bg-credora-orange/10">
              <FileText className="h-5 w-5 text-credora-orange" />
            </div>
            <div>
              <h3 className="text-lg font-semibold text-white">Comprehensive Report</h3>
              <p className="text-sm text-gray-500">Detailed analysis with strategic recommendations</p>
            </div>
          </div>

          {/* Report Card */}
          <div className="rounded-xl bg-[#282828] border border-[#333] p-5 mb-5 transition-all duration-200 hover:border-credora-orange/30">
            <div className="flex items-center gap-4">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-credora-orange to-credora-red flex-shrink-0">
                <FileText className="h-6 w-6 text-white" />
              </div>
              <div className="flex-1 min-w-0">
                <div className="font-semibold text-white mb-1">Competitor Analysis Report</div>
                <div className="text-sm text-gray-500 truncate">
                  {result.report_path}
                </div>
              </div>
              <div className="flex gap-2 flex-shrink-0">
                <button
                  onClick={handleViewFullReport}
                  className="px-4 py-2 bg-[#333] border border-[#444] text-gray-300 rounded-xl text-sm font-medium hover:border-credora-orange/30 hover:text-credora-orange transition-all duration-200 flex items-center gap-2"
                >
                  <Eye className="h-4 w-4" />
                  View
                </button>
                <button
                  onClick={handleDownloadReport}
                  disabled={isDownloading}
                  className="px-4 py-2 bg-gradient-to-r from-credora-orange to-credora-red text-white rounded-xl text-sm font-medium hover:shadow-lg hover:shadow-credora-orange/25 hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 flex items-center gap-2"
                >
                  {isDownloading ? (
                    <>
                      <Loader2 className="h-4 w-4 animate-spin" />
                      Downloading...
                    </>
                  ) : (
                    <>
                      <Download className="h-4 w-4" />
                      Download
                    </>
                  )}
                </button>
              </div>
            </div>
          </div>

          {/* Download Error */}
          {downloadError && (
            <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/30 mb-5 animate-slide-up">
              <div className="flex items-start gap-3">
                <AlertCircle className="h-5 w-5 text-red-400 mt-0.5 flex-shrink-0" />
                <div>
                  <p className="text-sm font-medium text-red-400">Download Failed</p>
                  <p className="text-xs text-gray-400 mt-1">{downloadError}</p>
                </div>
              </div>
            </div>
          )}

          {/* Report Features */}
          <div className="grid grid-cols-2 gap-3">
            {[
              { icon: Sparkles, text: "Executive Summary" },
              { icon: Users, text: "Competitor Profiles" },
              { icon: Target, text: "Strategy Analysis" },
              { icon: BarChart3, text: "AI Recommendations" }
            ].map((feature, index) => (
              <div key={index} className="flex items-center gap-2.5 text-sm text-gray-400 hover:text-white transition-colors">
                <CheckCircle className="h-4 w-4 text-emerald-400 flex-shrink-0" />
                <span>{feature.text}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Error Details */}
      {!isSuccess && (
        <div className="p-5 rounded-xl bg-red-500/10 border border-red-500/30 animate-slide-up">
          <div className="flex items-start gap-3">
            <AlertCircle className="h-5 w-5 text-red-400 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-sm font-medium text-red-400 mb-1">Analysis Failed</p>
              <p className="text-xs text-gray-400">
                The analysis could not be completed. Please check your inputs and try again.
                If the problem persists, contact support.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex gap-3">
        <button
          onClick={onReset}
          className="flex-1 px-6 py-3.5 bg-[#282828] border border-[#333] text-gray-300 rounded-xl font-medium hover:border-credora-orange/30 hover:text-credora-orange transition-all duration-200 flex items-center justify-center gap-2"
        >
          <Users className="h-5 w-5" />
          Analyze Another Business
        </button>
        
        {isSuccess && (
          <>
            <button
              onClick={handleViewFullReport}
              className="px-6 py-3.5 bg-[#282828] border border-[#333] text-gray-300 rounded-xl font-medium hover:border-credora-orange/30 hover:text-credora-orange transition-all duration-200 flex items-center gap-2"
            >
              <ExternalLink className="h-5 w-5" />
              View Report
            </button>
            <button
              onClick={handleShareResults}
              className="px-6 py-3.5 bg-[#282828] border border-[#333] text-gray-300 rounded-xl font-medium hover:border-credora-orange/30 hover:text-credora-orange transition-all duration-200 flex items-center gap-2"
            >
              <Globe className="h-5 w-5" />
              Share Results
            </button>
          </>
        )}
      </div>

      {/* Report Viewer Modal */}
      {result.report_path && (
        <ReportViewer
          reportPath={result.report_path}
          businessName={businessName}
          isOpen={isReportViewerOpen}
          onClose={() => setIsReportViewerOpen(false)}
        />
      )}
    </div>
  );
}
