/**
 * Component for displaying competitor analysis results
 */

import { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { 
  CheckCircle, 
  FileText, 
  Download, 
  ExternalLink, 
  TrendingUp,
  Users,
  AlertCircle,
  Eye,
  Globe,
  Loader2
} from "lucide-react";
import { type CompetitorAnalysisResponse } from "@/lib/api/competitor";
import { ReportViewer } from "./ReportViewer";
import { downloadReport } from "@/lib/api/competitor";

interface CompetitorResultsProps {
  result: CompetitorAnalysisResponse;
  onReset: () => void;
  businessName: string;
}

export function CompetitorResults({ result, onReset, businessName }: CompetitorResultsProps) {
  const [isReportViewerOpen, setIsReportViewerOpen] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  
  const isSuccess = result.status === "success";
  
  const handleDownloadReport = async () => {
    if (!result.report_path) return;
    
    setIsDownloading(true);
    setDownloadError(null);
    
    try {
      const blob = await downloadReport(result.report_path);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = result.report_path.split('/').pop() || 'competitor_report.txt';
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      setDownloadError(err instanceof Error ? err.message : "Failed to download report");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleViewFullReport = () => {
    setIsReportViewerOpen(true);
  };

  const handleShareResults = () => {
    // Create shareable summary
    const shareText = `Competitor Analysis Results for ${businessName}:\n\n${result.result}\n\nGenerated by Credora Analytics`;
    
    if (navigator.share) {
      navigator.share({
        title: `Competitor Analysis - ${businessName}`,
        text: shareText,
      });
    } else {
      // Fallback: copy to clipboard
      navigator.clipboard.writeText(shareText).then(() => {
        alert("Results copied to clipboard!");
      });
    }
  };

  return (
    <div className="space-y-6">
      {/* Success/Error Status */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            {isSuccess ? (
              <CheckCircle className="h-5 w-5 text-green-500" />
            ) : (
              <AlertCircle className="h-5 w-5 text-red-500" />
            )}
            Analysis {isSuccess ? "Complete" : "Failed"}
          </CardTitle>
          <CardDescription>
            {result.message}
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {/* Status Badge */}
          <div className="flex items-center gap-2">
            <Badge variant={isSuccess ? "default" : "destructive"}>
              {result.status.toUpperCase()}
            </Badge>
            {isSuccess && (
              <span className="text-sm text-muted-foreground">
                {result.competitors_analyzed} competitors analyzed
              </span>
            )}
          </div>

          {/* Business Info */}
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <Users className="h-4 w-4" />
            Analysis for: <span className="font-medium">{businessName}</span>
          </div>
        </CardContent>
      </Card>

      {/* Results Content */}
      {isSuccess && result.result && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <TrendingUp className="h-5 w-5" />
              Key Findings
            </CardTitle>
            <CardDescription>
              Strategic insights from competitor analysis
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="rounded-lg bg-muted p-4">
              <div className="prose prose-sm max-w-none">
                <div className="whitespace-pre-wrap text-sm">
                  {result.result}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Report Download */}
      {isSuccess && result.report_path && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Comprehensive Report
            </CardTitle>
            <CardDescription>
              Detailed analysis with strategic recommendations
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center gap-3 p-4 border rounded-lg bg-card">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                <FileText className="h-5 w-5 text-primary" />
              </div>
              <div className="flex-1">
                <div className="font-medium">Competitor Analysis Report</div>
                <div className="text-sm text-muted-foreground">
                  {result.report_path}
                </div>
              </div>
              <div className="flex gap-2">
                <Button size="sm" variant="outline" onClick={handleViewFullReport}>
                  <Eye className="mr-2 h-4 w-4" />
                  View
                </Button>
                <Button 
                  size="sm" 
                  onClick={handleDownloadReport}
                  disabled={isDownloading}
                >
                  {isDownloading ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Download className="mr-2 h-4 w-4" />
                  )}
                  {isDownloading ? "Downloading..." : "Download"}
                </Button>
              </div>
            </div>

            {/* Download Error */}
            {downloadError && (
              <Alert variant="destructive">
                <AlertCircle className="h-4 w-4" />
                <AlertDescription>{downloadError}</AlertDescription>
              </Alert>
            )}

            {/* Report Features */}
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-500" />
                Executive Summary
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-500" />
                Competitor Profiles
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-500" />
                Strategy Analysis
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle className="h-4 w-4 text-green-500" />
                AI Recommendations
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Error Details */}
      {!isSuccess && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>
            The analysis could not be completed. Please check your inputs and try again.
            If the problem persists, contact support.
          </AlertDescription>
        </Alert>
      )}

      {/* Action Buttons */}
      <div className="flex gap-3">
        <Button onClick={onReset} variant="outline" className="flex-1">
          <Users className="mr-2 h-4 w-4" />
          Analyze Another Business
        </Button>
        
        {isSuccess && (
          <>
            <Button variant="outline" onClick={handleViewFullReport}>
              <ExternalLink className="mr-2 h-4 w-4" />
              View Report
            </Button>
            <Button variant="outline" onClick={handleShareResults}>
              <Globe className="mr-2 h-4 w-4" />
              Share Results
            </Button>
          </>
        )}
      </div>

      {/* Report Viewer Modal */}
      {result.report_path && (
        <ReportViewer
          reportPath={result.report_path}
          businessName={businessName}
          isOpen={isReportViewerOpen}
          onClose={() => setIsReportViewerOpen(false)}
        />
      )}
    </div>
  );
}